version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     # - POSTGRES_DB=CatalogDb
      - POSTGRES_MULTIPLE_DATABASES=CatalogDb;BasketDb
    restart: unless-stopped
    ports:
        - "5432:5432"
    volumes:
      - ./postgres_catalog:/var/lib/postgresql/data/
  # basketdb:
  #   container_name: basketdb
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=BasketDb
  #   restart: always
  #   ports:
  #       - "5433:5432"
  #   volumes:
  #     - ./postgres_basket:/var/lib/postgresql/data/
  distributedcache:
   container_name: distributedcache
   restart: always
   ports:
   - "6379:6379"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "2020:80"
    depends_on:
      - catalogdb  # Ensures pgAdmin starts after PostgreSQL
      - basketdb
       
  # sqlite:
  #   container_name: sqlite
  #   image: sqlite:latest
  #   restart: always
  #   command: sqlite3 discount.db
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./sqlite:/var/lib/sqlite/data

  dokan.service.catalog:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalog;Port=5432;Database=CatalogDb;Username=postgres;Password=postgres
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  dokan.service.basket:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=BasketDb;Username=postgres;Password=postgres
      - ConnectionStrings__Redis=distributedcache:6379      
      - GrpcSettings__DiscountUrl=https://Dokan.Service.Discount:8081
    depends_on:
      - basketdb
      - distributedcache
      - dokan.service.discount
    ports:
      - "7000:8080"
      - "7070:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  dokan.service.discount:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081            
      - ConnectionStrings__Database=Data Source=discountdb 
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
